name: Label Issues
on:
  issues:
    types:
      - reopend
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label Issues
        uses: andymckay/labeler@master
        with:
          add-lables: "New"
          repo-token: ${{ secret.GITHUB_TOKEN }}
